name = "GenieSessionFileSession"
uuid = "5c4fdc26-39e3-47cf-9034-e533e09961c2"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
