name = "GenieSessionFileSession"
uuid = "5c4fdc26-39e3-47cf-9034-e533e09961c2"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "2.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieSession = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Genie = "6"
GenieSession = "2"
julia = "1.6"
